import type { NextPage } from "next"
import Head from "next/head"
import { getAllArticles } from "@/api/index"
import Bio from "@/components/bio"
import Brief from "@/components/brief"
import Container from "@/components/container"
import Footer from "@/components/footer"
import Header from "@/components/header"
import { Article } from "@/types"
import config from "@/kapok.config"

interface HomeProps {
  articles: Article[]
}

const Home: NextPage<HomeProps> = ({ articles }) => {
  return (
    <Container>
      <Head>
        <title>{config.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Bio />
      <main>
        <Brief articles={articles} />
      </main>
      <Footer />
    </Container>
  )
}

export async function getStaticProps() {
  const articles = getAllArticles([
    "link",
    "filename",
    "title",
    "date",
    "brief",
  ])
  return {
    props: { articles },
  }
}

export default Home
