import type { NextPage } from "next"
import Head from "next/head"
import Bio from "../components/bio"
import Brief from "../components/brief"
import Container from "../components/container"
import Footer from "../components/footer"
import Header from "../components/header"

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>inn.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Bio />
      <main>
        <Brief />
      </main>
      <Footer />
    </Container>
  )
}

export default Home
