import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import { getAllArticles, getArticleByFilename } from "../api"
import HtmlRender from "../components/HtmlRender"
import styles from "../styles/Home.module.css"
import markdownToHtml from "../utils/markdownToHtml"

const Test: NextPage = (props: any) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <HtmlRender content={props.post.content} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getStaticProps() {
  const post = getArticleByFilename("hello-word", [
    "title",
    "date",
    "content",
    "description",
  ])

  const content = await markdownToHtml(post.content || "")

  return {
    props: {
      post: {
        ...post,
        content,
      },
    },
  }
}

export default Test
